### ISSUE TITLE
Infra: Build Database Schema

### ISSUE THREAD

**Issue by nadinelin** [ConnieML/Connie-RTC#14]
Should be done in a meeting with the backend engineers and Caleb

**Comment by ZzRanger** [comment]
![Image](https://github.com/ConnieML/Connie-RTC/assets/47403443/70f6c112-e26a-4bff-9006-8b7c9b20f1e5)
![Image](https://github.com/ConnieML/Connie-RTC/assets/47403443/77c43e29-8350-4bb1-9ca7-b29f6cc335d3)
