### ISSUE TITLE
Twilio: Manipulate the Task Router API

### ISSUE THREAD

**Issue by ZzRanger** [ConnieML/Connie-RTC#19]
Build a set of endpoints to manipulate a workspace instance on Twilio. You should be able to do the following things:

- CRUD operations on a worker
- CRUD operations on TasksQueue
- CRUD operations on Tasks
- CRUD operations on Workflows
 - CRUD operations on a workspace

Bonus: create a minimal frontend UI to modify a workspace

**Comment by qu8n** [comment]
@ZzRanger [The repo](https://github.com/qu8n/twilio-taskrouter-wrapper) is ready for your review. All these resources are available as API endpoints. There's a UI for managing Workspaces as a reference point for Nhi. Note that I added the Activities API endpoint to help with updating Workspaces.
