### ISSUE TITLE
Build Queues Stats Dashboard Functionality

### ISSUE THREAD

**Issue by ZzRanger** [ConnieML/Connie-RTC#25]
We're still waiting for mockups to be finalized and to get a final list of functionality. For now, just figure out how to implement the functionality on the screen and create a barebones UI for it.

![Image](https://user-images.githubusercontent.com/47403443/246306695-557c8974-b1da-4981-91c4-3210a7d6b567.png)

**Comment by qu8n** [comment]
Dashboard design for ref [here](https://www.figma.com/file/liDDUlZBbTbxQlJP1PugZG/ASA-Design?type=design&node-id=128-30854&mode=design).

My plan:

- Create a new page for this dashboard under `/pages/queues-stats/index.tsx`
- Request the required data on the frontend from the existing internal Tasks, TasksQueues, and Workers API endpoints
- Perform calculations on pulled data using newly defined util functions
- Display stats minimally without any styling

Edit: this plan is outdated. See [my PR](https://github.com/ConnieML/Connie-RTC/compare/task-queues-stats-dashboard?expand=1)'s description for the updated data flow.
