### ISSUE TITLE
Add Form Input Validation

### ISSUE THREAD

**Issue by ZzRanger** [ConnieML/Connie-RTC#48]
We currently don't have any client-side input validation for the two screens below. We should provide the user with some sort of validation to provide a better user experience. If more screens get implemented, add the screens that need input validation below.

![Add Task Queues(1)](https://github.com/ConnieML/Connie-RTC/assets/47403443/bd503b34-86b0-4525-97af-5718501daf18)
![Edit Users](https://github.com/ConnieML/Connie-RTC/assets/47403443/eda1851e-075e-4973-988c-1321766e9354)

**Comment by WillieCubed** [comment]
Closing due to changing needs of Connie Phase II
