### ISSUE TITLE
Limit Access to Admin Settings based on role

### ISSUE THREAD

**Issue by cam-obrien** [ConnieML/Connie-RTC#68]
Currently, Users with agent-level status are able to access the admin settings and make changes. We need to edit the navigation bar to remove the admin settings page from the options if the current user is not an admin. Further, if a user hardcodes the admin settings path into the url a page should inform them they don't have access to that page.

Potential future issue:
Agent level settings page

**Comment by WillieCubed** [comment]
Closing due to changing needs of Connie Phase II
