### ISSUE TITLE
Implement Checks to Ensure Logged in Users are also Twilio Workers

### ISSUE THREAD

**Issue by cam-obrien** [ConnieML/Connie-RTC#69]
Currently, the majority of our listed users in Connie exist in the Okta database but are not twilio workers inside of the workspace. This leads to them not being able to access the call center. We have to check if the user signed in from okta exists in the twilio workspace and if not give them the option to be added to the twilio workspace. Here is a viable approach:

1. On login check if the user has a value in the EmployeeNumber Okta Attribute (only perform the following if they don't have the attribute)

2. Notify them they don't exist as a twilio worker and ask them if they would like to be added to the workspace (or just add them  - will check with team on that)

3. Call the internal Twilio api to create a worker with their name (make sure to check if there is already a worker with their name)

4. Take the worker sid from the newly created worker and append it to the Okta profile under the employeeNumber attribute

**Comment by WillieCubed** [comment]
Closing due to changing needs of Connie Phase II
